name: safesafe

configs:
  Dev: debug
  Stage: release
  Live: release

settings:
  CODE_SIGN_STYLE: Manual
  MARKETING_VERSION: "3.0.0"
  CURRENT_PROJECT_VERSION: 40

targets:
  safesafe:
    type: application
    platform: iOS
    deploymentTarget: "12.1"
    configFiles:
      Dev: safesafe/Resources/Dev/dev.xcconfig
      Stage: safesafe/Resources/Stage/stage.xcconfig
      Live: safesafe/Resources/Live/live.xcconfig
    preBuildScripts:
      - name: IncludeGooglePlists
        script: ls
    sources: 
      - safesafe
      - ["safesafe Live.entitlements", "safesafe Dev.entitlements"]
      - path: Submodules/opentrace-ios/OpenTrace/Constants
        group: OpenTrace
        includes: PushNotificationConstants.swift
      - path: Submodules/opentrace-ios/OpenTrace/Utils
        group: OpenTrace
        includes: [FirebaseAPIs.swift, PlistHelper.swift]
      - path: Submodules/opentrace-ios/OpenTrace/Bluetrace
        group: OpenTrace
        excludes: [BluetraceConfig.swift, BluetraceManager.swift, CentralController.swift]
      - path: "Submodules/opentrace-ios/OpenTrace/Power saver/PogoInstructionsViewController.swift"
        group: OpenTrace/PowerSaver
      - path: safesafe/Resources
