name: safesafe

configs:
  Dev: debug
  Stage: release
  Live: release

settings:
  CODE_SIGN_STYLE: Manual
  MARKETING_VERSION: "3.0.0"
  CURRENT_PROJECT_VERSION: 40

targets:
  safesafe:
    type: application
    platform: iOS
    deploymentTarget: "12.1"
    configFiles:
      Dev: safesafe/Resources/Dev/dev.xcconfig
      Stage: safesafe/Resources/Stage/stage.xcconfig
      Live: safesafe/Resources/Live/live.xcconfig
    sources: 
      - safesafe
      - ["safesafe Live.entitlements", "safesafe Dev.entitlements"]
      - path: Submodules/opentrace-ios/OpenTrace/Utils
        group: OpenTrace
        includes: [FirebaseAPIs.swift]
      - path: Submodules/opentrace-ios/OpenTrace/Bluetrace
        group: OpenTrace
        excludes: [
            BluetraceConfig.swift,
            BluetraceManager.swift,
            BlueTraceLocalNotifications.swift,
            CentralController.swift,
            EncounterMessageManager.swift,
            Protocol/v2/BluetraceV2.swift
        ]
    preBuildScripts:
      - name: CopyGooglePlist
        path: Scripts/CopyGooglePlist.sh 
    postBuildScripts:
      - script:
          custom_sim=`xcrun simctl list | grep 'Custom Simulators' | awk -F'[()]' '{print $2}'`
          if [ ! -z "${custom_sim}" ] && [ "${TARGET_DEVICE_IDENTIFIER}" = "${custom_sim}" ]; then
          /bin/sh multipleSimulatorsStartup.sh
          fi
        name: "Custom sims"
