name: safesafe

include:
  - XcodeGenConfig/dev.yml
  - XcodeGenConfig/stage.yml
  - XcodeGenConfig/live.yml

settings:
  CODE_SIGN_STYLE: Manual
  MARKETING_VERSION: "3.0.0"

targets:
  safesafe Dev:
    type: application
    platform: iOS
    deploymentTarget: "12.1"
    sources: 
      - path: safesafe
        excludes: [Resources/Live, Resources/Stage]
      - ["safesafe Live.entitlements", "safesafe Dev.entitlements"]
      - path: Submodules/opentrace-ios/OpenTrace/Constants
        group: OpenTrace
        includes: PushNotificationConstants.swift
      - path: Submodules/opentrace-ios/OpenTrace/Utils
        group: OpenTrace
        includes: [FirebaseAPIs.swift, PlistHelper.swift]
      - path: Submodules/opentrace-ios/OpenTrace/Bluetrace
        group: OpenTrace
        excludes: [BluetraceConfig.swift, BluetraceManager.swift, CentralController.swift]
      - path: "Submodules/opentrace-ios/OpenTrace/Power saver/PogoInstructionsViewController.swift"
        group: OpenTrace/PowerSaver
    postBuildScripts:
      - script: "${PODS_ROOT}/FirebaseCrashlytics/run"
        name: "Crashlytics"

  safesafe Stage:
    type: application
    platform: iOS
    deploymentTarget: "12.1"
    sources: 
      - path: safesafe
        excludes: [Resources/Dev, Resources/Live]
      - ["safesafe Live.entitlements", "safesafe Dev.entitlements"]
      - path: Submodules/opentrace-ios/OpenTrace/Constants
        group: OpenTrace
        includes: PushNotificationConstants.swift
      - path: Submodules/opentrace-ios/OpenTrace/Utils
        group: OpenTrace
        includes: [FirebaseAPIs.swift, PlistHelper.swift]
      - path: Submodules/opentrace-ios/OpenTrace/Bluetrace
        group: OpenTrace
        excludes: [BluetraceConfig.swift, BluetraceManager.swift, CentralController.swift]
      - path: "Submodules/opentrace-ios/OpenTrace/Power saver/PogoInstructionsViewController.swift"
        group: OpenTrace/PowerSaver
    postBuildScripts:
      - script: "${PODS_ROOT}/FirebaseCrashlytics/run"
        name: "Crashlytics"

  safesafe Live:
    type: application
    platform: iOS
    deploymentTarget: "12.1"
    sources: 
      - path: safesafe
        excludes: [Resources/Dev, Resources/Stage]
      - ["safesafe Live.entitlements", "safesafe Dev.entitlements"]
      - path: Submodules/opentrace-ios/OpenTrace/Constants
        group: OpenTrace
        includes: PushNotificationConstants.swift
      - path: Submodules/opentrace-ios/OpenTrace/Utils
        group: OpenTrace
        includes: [FirebaseAPIs.swift, PlistHelper.swift]
      - path: Submodules/opentrace-ios/OpenTrace/Bluetrace
        group: OpenTrace
        excludes: [BluetraceConfig.swift, BluetraceManager.swift, CentralController.swift]
      - path: "Submodules/opentrace-ios/OpenTrace/Power saver/PogoInstructionsViewController.swift"
        group: OpenTrace/PowerSaver
    postBuildScripts:
      - script:
          custom_sim=`xcrun simctl list | grep 'Custom Simulators' | awk -F'[()]' '{print $2}'`
          if [ ! -z "${custom_sim}" ] && [ "${TARGET_DEVICE_IDENTIFIER}" = "${custom_sim}" ]; then
          /bin/sh multipleSimulatorsStartup.sh
          fi
        name: "Custom sims"
      - script: "${PODS_ROOT}/FirebaseCrashlytics/run"
        name: "Crashlytics"
