name: safesafe

configs:
  StageDebug: debug
  Stage: release
  LiveDebug: debug
  Live: release
  StageAdhoc: release

schemes:

  safesafe Stage:
    build:
      targets: 
        safesafe: all
    run: 
      config: StageDebug
    archive:
      config: Stage

  safesafe Live:
    build:
      targets:
        safesafe: all
    run:
      config: LiveDebug
    archive:
      config: Live

targets:
  # Target for Mutable Push Notifications Extension
  #
  PushMutableContent:
    settings:
      CODE_SIGN_STYLE: Manual
      MARKETING_VERSION: "4.13.0"
      CURRENT_PROJECT_VERSION: 746
      TARGETED_DEVICE_FAMILY: 1,2
    type: app-extension
    platform: iOS
    deploymentTarget: "12.1"
    configFiles:
      Stage: safesafe/Resources/Extensions/apns-stage-mutablecontent.xcconfig
      StageDebug: safesafe/Resources/Extensions/apns-stage-mutablecontent-dev.xcconfig
      Live: safesafe/Resources/Extensions/apns-mutablecontent.xcconfig
      LiveDebug: safesafe/Resources/Extensions/apns-mutablecontent-dev.xcconfig
    sources:
      - path: PushMutableContent
        name: "PushMutableContent"
      - path: safesafe/Common/Helpers/Notifications
        group: safesafe/Common/Helpers
        excludes: 
          - NotificationHistoryWorker.swift
          - Models/PushNotificationHistoryModel.swift
      - path: safesafe/Services/StoredDefaults.swift
        group: safesafe/Services
      - path: safesafe/Language/LanguageController.swift
        group: safesafe/Language
      - path: safesafe/Resources/Extensions
        group: safesafe/Resources
      - path: safesafe/Models/DashboardStatsAPIResponse.swift
        group: safesafe/Models
  # Main app target
  #
  safesafe:
    type: application
    platform: iOS
    deploymentTarget: "12.1"
    settings:
        CODE_SIGN_STYLE: Manual
        MARKETING_VERSION: "4.13.0"
        CURRENT_PROJECT_VERSION: 746
        TARGETED_DEVICE_FAMILY: 1
        SWIFT_OBJC_BRIDGING_HEADER: $(PROJECT_DIR)/safesafe/App/safesafe-Bridging-Header.h
    configFiles:
      StageDebug: safesafe/Resources/Stage/stageDebug.xcconfig
      Stage: safesafe/Resources/Stage/stage.xcconfig
      StageAdhoc: safesafe/Resources/Stage/stageAdhoc.xcconfig
      LiveDebug: safesafe/Resources/Live/liveDebug.xcconfig
      Live: safesafe/Resources/Live/live.xcconfig
    sources: 
      - path: safesafe
        name: "safesafe"
        excludes:
          - "Resources/translations"
          - "Resources/pwa"
          - "Resources/Stage/Config-stage.plist"
          - "Resources/Live/Config-live.plist"
          - "Resources/Stage/GoogleService-Info-Stage.plist"
          - "Resources/Live/GoogleService-Info-Live.plist"
          - "Info-stage.plist"
          - "Info-live.plist"
      - path: safesafe/Resources/pwa
        type: folder
      - path: safesafe/Resources/translations
        type: folder
    dependencies:
      - target: PushMutableContent
        codesign: true
        embed: true
    preBuildScripts:
      - name: CopyGooglePlist
        path: Scripts/CopyGooglePlist.sh
      - name: CopyConfigPlist
        path: Scripts/CopyConfigPlist.sh 
