name: safesafe

include:
  - XcodeGenConfig/dev.yml
  - XcodeGenConfig/stage.yml
  - XcodeGenConfig/live.yml

configs:
  Dev: debug
  Stage: release
  Live: release

settings:
  CODE_SIGN_STYLE: Manual
  MARKETING_VERSION: "3.0.0"
  CURRENT_PROJECT_VERSION: 40

schemes:
  safesafe Dev:
    build: 
      targets: 
        safesafe Dev: all
    run:
      config: Dev
    archive:
      config: Dev

  safesafe Stage:
    build: 
      targets: 
        safesafe Stage: all
    run:
      config: Stage
    archive:
      config: Stage

  safesafe Live:
    build: 
      targets: 
        safesafe Live: all
    run:
      config: Live
    archive:
      config: Live

targets:
  safesafe Dev:
    type: application
    platform: iOS
    deploymentTarget: "12.1"
    sources: 
      - path: safesafe
        excludes: [Resources/Live, Resources/Stage]
      - ["safesafe Live.entitlements", "safesafe Dev.entitlements"]
      - path: Submodules/opentrace-ios/OpenTrace/Utils
        group: OpenTrace
        includes: [FirebaseAPIs.swift]
      - path: Submodules/opentrace-ios/OpenTrace/Bluetrace
        group: OpenTrace
        excludes: [
            BluetraceConfig.swift,
            BluetraceManager.swift,
            BlueTraceLocalNotifications.swift,
            CentralController.swift,
            EncounterMessageManager.swift,
            Protocol/v2/BluetraceV2.swift
        ]

  safesafe Stage:
    type: application
    platform: iOS
    deploymentTarget: "12.1"
    sources: 
      - path: safesafe
        excludes: [Resources/Dev, Resources/Live]
      - ["safesafe Live.entitlements", "safesafe Dev.entitlements"]
      - path: Submodules/opentrace-ios/OpenTrace/Utils
        group: OpenTrace
        includes: [FirebaseAPIs.swift]
      - path: Submodules/opentrace-ios/OpenTrace/Bluetrace
        group: OpenTrace
        excludes: [
            BluetraceConfig.swift,
            BluetraceManager.swift,
            BlueTraceLocalNotifications.swift,
            CentralController.swift,
            EncounterMessageManager.swift,
            Protocol/v2/BluetraceV2.swift
        ]

  safesafe Live:
    type: application
    platform: iOS
    deploymentTarget: "12.1"
    sources: 
      - path: safesafe
        excludes: [Resources/Dev, Resources/Stage]
      - ["safesafe Live.entitlements", "safesafe Dev.entitlements"]
      - path: Submodules/opentrace-ios/OpenTrace/Utils
        group: OpenTrace
        includes: [FirebaseAPIs.swift]
      - path: Submodules/opentrace-ios/OpenTrace/Bluetrace
        group: OpenTrace
        excludes: [
            BluetraceConfig.swift,
            BluetraceManager.swift,
            BlueTraceLocalNotifications.swift,
            CentralController.swift,
            EncounterMessageManager.swift,
            Protocol/v2/BluetraceV2.swift
        ]
    postBuildScripts:
      - script:
          custom_sim=`xcrun simctl list | grep 'Custom Simulators' | awk -F'[()]' '{print $2}'`
          if [ ! -z "${custom_sim}" ] && [ "${TARGET_DEVICE_IDENTIFIER}" = "${custom_sim}" ]; then
          /bin/sh multipleSimulatorsStartup.sh
          fi
        name: "Custom sims"
