name: safesafe

configs:
  Dev: debug
  DevDist: release
  StageDebug: debug
  StageScreencast: release
  Stage: release
  LiveDebug: debug
  Live: release
  LiveAdhoc: release #That's a build with Live PWA URL but with debug console

settings:
  CODE_SIGN_STYLE: Manual
  MARKETING_VERSION: "4.9.0"
  CURRENT_PROJECT_VERSION: 745
schemes:
  safesafe Dev:
    build:
      targets: 
        safesafe: all
    run:
      config: Dev

  safesafe Stage:
    build:
      targets: 
        safesafe: all
    run: 
      config: StageDebug
    archive:
      config: Stage

  safesafe Live:
    build:
      targets:
        safesafe: all
    run:
      config: LiveDebug
    archive:
      config: Live

targets:
  PushMutableContent:
    TARGETED_DEVICE_FAMILY: 1,2
    type: app-extension
    platform: iOS
    deploymentTarget: "12.1"
    configFiles:
      StageDebug: safesafe/Resources/Extensions/apns-mutablecontent.xcconfig
    sources:
      - path: PushMutableContent
        name: "PushMutableContent"
      - path: safesafe/Services/StoredDefaults.swift
      - path: safesafe/Language/LanguageController.swift
  safesafe:
    type: application
    platform: iOS
    deploymentTarget: "12.1"
    settings:
        TARGETED_DEVICE_FAMILY: 1
        SWIFT_OBJC_BRIDGING_HEADER: $(PROJECT_DIR)/safesafe/App/safesafe-Bridging-Header.h
    configFiles:
      Dev: safesafe/Resources/Dev/dev.xcconfig
      DevDist: safesafe/Resources/Dev/devDist.xcconfig
      StageScreencast: safesafe/Resources/Stage/stageScreencast.xcconfig
      StageDebug: safesafe/Resources/Stage/stageDebug.xcconfig
      Stage: safesafe/Resources/Stage/stage.xcconfig
      LiveDebug: safesafe/Resources/Live/liveDebug.xcconfig
      LiveAdhoc: safesafe/Resources/Live/liveAdhoc.xcconfig
      Live: safesafe/Resources/Live/live.xcconfig
    sources: 
      - path: safesafe
        name: "safesafe"
        excludes:
          - "Resources/translations"
          - "Resources/pwa"
          - "Resources/Dev/Config-dev.plist"
          - "Resources/Stage/Config-stage.plist"
          - "Resources/Live/Config-live.plist"
          - "Resources/Dev/GoogleService-Info-Dev.plist"
          - "Resources/Stage/GoogleService-Info-Stage.plist"
          - "Resources/Live/GoogleService-Info-Live.plist"
          - "Info-dev.plist"
          - "Info-stage.plist"
          - "Info-live.plist"
      - path: safesafe/Resources/pwa
        type: folder
      - path: safesafe/Resources/translations
        type: folder
    dependencies:
      - target: PushMutableContent
        codesign: true
        embed: true
    preBuildScripts:
      - name: CopyGooglePlist
        path: Scripts/CopyGooglePlist.sh
      - name: CopyConfigPlist
        path: Scripts/CopyConfigPlist.sh 
